steps:
- id: "clone kritis repo"
  name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/grafeas/kritis.git']
## 
- id: "build signer binary"
  name: 'gcr.io/cloud-builders/go:debian'
  args: ['build', '-o', 'out/signer', './cmd/kritis/signer']
  env: ['PROJECT_ROOT=github.com/grafeas/kritis']
  dir: 'kritis'
##
- id: "build signer image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/cool-lambda-430915-g2/test-repo/signer-binary:v1', '.']
##
- id: "publish signer image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/cool-lambda-430915-g2/test-repo/signer-binary:v1']
options:
  logging: CLOUD_LOGGING_ONLY
